/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carpurchase;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author QP
 */
public class AdminPanel extends javax.swing.JFrame {
    Cart cart = new Cart();
    Object[] row = new Object[5];
    Cars car = new Cars();
    
    public static int currentCarNumber = 0;
    public static String[][] carInformations = new String[100][5];
 
    public AdminPanel() {
        initComponents();
        
        currentCarNumber = car.getCurrentCarNumber();
        carInformations = car.getCarInformation();
                
        for (int i = 0; i < currentCarNumber; i++)
        {
            for (int j = 0; j < 5; j++)
            {
                row[j] = carInformations[i][j];
            }
            
            DefaultTableModel model = (DefaultTableModel)CarsTable.getModel();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SaveBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        EditBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        modalText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        CarsTable = new javax.swing.JTable();
        DeleteBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        statusComboBox = new javax.swing.JComboBox<>();
        yearText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        brandText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        priceText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SaveBtn.setBackground(new java.awt.Color(204, 255, 255));
        SaveBtn.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        SaveBtn.setText("Add");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 109, -1));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Status");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Price");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Manage Car");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 12, 257, -1));

        EditBtn.setBackground(new java.awt.Color(204, 255, 255));
        EditBtn.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        EditBtn.setText("Edit");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });
        jPanel1.add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 106, -1));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Year");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, -1, -1));

        modalText.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jPanel1.add(modalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 160, -1));

        CarsTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false;
            }
        };
        CarsTable.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        CarsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Modal", "Year", "Price", "Status"
            }
        ));
        CarsTable.setRowHeight(25);
        CarsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(CarsTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 948, -1));

        DeleteBtn.setBackground(new java.awt.Color(204, 255, 255));
        DeleteBtn.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 109, -1));

        ResetBtn.setBackground(new java.awt.Color(204, 255, 255));
        ResetBtn.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 190, 100, -1));

        statusComboBox.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Booked" }));
        jPanel1.add(statusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 146, -1));

        yearText.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jPanel1.add(yearText, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 130, 153, -1));

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));
        jPanel4.setForeground(new java.awt.Color(255, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 37, -1, -1));
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 63, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 625, 127, -1));

        jButton5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton5.setText("Customer Panel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 309, -1, -1));

        jLabel1.setToolTipText("");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 43, 127, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpurchase/adminPanel.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 49, 176, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpurchase/blue.png"))); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 720));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 720));

        brandText.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jPanel1.add(brandText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 161, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Brand");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        priceText.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jPanel1.add(priceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 130, 156, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Modal");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1269, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpurchase/grey1.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1100, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
            new Login().setVisible(true);
            this.dispose();
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        Reset();
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel)CarsTable.getModel();
        int i = CarsTable.getSelectedRow();
        
        if(i >= 0)
        {
            model.removeRow(i);
            try {
                car.deleteCar(i);
            } catch (IOException ex) {
                Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if(brandText.getText().isEmpty() || modalText.getText().isEmpty() || priceText.getText().isEmpty() ||yearText.getText().isEmpty() || statusComboBox.getSelectedIndex() == -1)
        {
            JOptionPane.showMessageDialog(this, "Select A Car To Be Deleted");
        }else{
        
      
           JOptionPane.showMessageDialog(this, "Car Deleted Successfully");
           
            Reset();
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed

        DefaultTableModel model = (DefaultTableModel)CarsTable.getModel();
        int i = CarsTable.getSelectedRow();
               
        if(i >= 0) 
        {
            model.setValueAt(brandText.getText(), i, 0);
            model.setValueAt(modalText.getText(), i, 1);
            model.setValueAt(yearText.getText(), i, 2);
            model.setValueAt(priceText.getText(), i, 3);
            model.setValueAt(statusComboBox.getSelectedItem(), i, 4);
            
            row[0] = brandText.getText();
            row[1] = modalText.getText();
            row[2] = yearText.getText();
            row[3] = priceText.getText();
            row[4] = statusComboBox.getSelectedItem();
            try {
                car.editCar(row, i);
            } catch (IOException ex) {
                Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if(brandText.getText().isEmpty() || modalText.getText().isEmpty() || priceText.getText().isEmpty() ||yearText.getText().isEmpty() || statusComboBox.getSelectedIndex() == -1)
        {
            JOptionPane.showMessageDialog(this, "Select A Car To Be Updated");
        }else{
        try {
      
           JOptionPane.showMessageDialog(this, "Car Updated Successfully");
           
            Reset();
        } catch (Exception e) {
            e.printStackTrace();
        }
         }

    }//GEN-LAST:event_EditBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        row[0] = brandText.getText();
        row[1] = modalText.getText();
        row[2] = yearText.getText();
        row[3] = priceText.getText();
        row[4] = statusComboBox.getSelectedItem();
                
        DefaultTableModel model = (DefaultTableModel)CarsTable.getModel();  
        
        try {
            if(!brandText.getText().equals("") && !modalText.getText().equals("") && !yearText.getText().equals("") && !priceText.getText().equals(""))
            {
                model.addRow(row);
                car.addCar(row);
                JOptionPane.showMessageDialog(this, "Car Added Successfully");
            }
            else{
                JOptionPane.showMessageDialog(this, "Missing Information");
            }
        } catch (IOException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void CarsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarsTableMouseClicked
       DefaultTableModel model = (DefaultTableModel)CarsTable.getModel();
       int MyIndex = CarsTable.getSelectedRow();
       brandText.setText(model.getValueAt(MyIndex, 0).toString());
       modalText.setText(model.getValueAt(MyIndex, 1).toString());
       yearText.setText(model.getValueAt(MyIndex, 2).toString());
       priceText.setText(model.getValueAt(MyIndex, 3).toString());
       statusComboBox.setSelectedItem(model.getValueAt(MyIndex, 4).toString());
    }//GEN-LAST:event_CarsTableMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new CustomerInformations().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        for (int i = (cart.getCurrentCartNumber() - 1); i >= 0; i--)
        {
            try {
                cart.deleteCart(i);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void Reset()
    {
        modalText.setText("");
        brandText.setText("");
        yearText.setText("");
        priceText.setText("");
        statusComboBox.setSelectedItem(0);
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CarsTable;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField brandText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField modalText;
    private javax.swing.JTextField priceText;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JTextField yearText;
    // End of variables declaration//GEN-END:variables
}
