
package carpurchase;

import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;


public class Payment extends javax.swing.JFrame {
    Cart cart = new Cart();
    int iPrice = 0;
    static double dMonthlyPrice = 0, dTotalPrice = 0;
    
        
    public Payment() {
        initComponents();
        iPrice = cart.getTotalCartPrice();
        priceText.setText(Integer.toString(iPrice) + " $");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        button2 = new javax.swing.JRadioButton();
        monthOptionBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        priceText = new javax.swing.JTextField();
        monthlyPriceText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        totalPriceText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cardNoPartText1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        button1 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        cardNoPartText2 = new javax.swing.JTextField();
        cardNoPartText3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cardNoPartText4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel6.setText("Cash Payment");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 160, -1, -1));

        buttonGroup2.add(button2);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, -1, -1));

        monthOptionBox.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        monthOptionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6 Month (+%5)", "12 Month (+%10)", "24 Month (+%20)" }));
        monthOptionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthOptionBoxActionPerformed(evt);
            }
        });
        jPanel1.add(monthOptionBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Price");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel8.setText("Installment Payment");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton1.setText("Confirm Purchase");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 530, 311, -1));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Total Price");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 530, 146, -1));

        priceText.setEditable(false);
        priceText.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        priceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextActionPerformed(evt);
            }
        });
        jPanel1.add(priceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 260, -1));

        monthlyPriceText.setEditable(false);
        monthlyPriceText.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        monthlyPriceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyPriceTextActionPerformed(evt);
            }
        });
        jPanel1.add(monthlyPriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, 218, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Payment");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Monthly Price");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 37, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 127, -1));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 68, -1, -1));
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 62, 133, -1));

        jButton7.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton7.setText("Main Menu");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 296, 178, -1));

        jButton5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton5.setText("My Cart");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 362, 178, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpurchase/payment.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpurchase/blue.png"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 670));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 670));

        totalPriceText.setEditable(false);
        totalPriceText.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jPanel1.add(totalPriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, 218, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Card No");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, -1));

        cardNoPartText1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jPanel1.add(cardNoPartText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 70, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 328, 178, -1));

        buttonGroup2.add(button1);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("X");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, -1, -1));

        cardNoPartText2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jPanel1.add(cardNoPartText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 70, -1));

        cardNoPartText3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jPanel1.add(cardNoPartText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 70, -1));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel7.setText("-");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel13.setText("-");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel16.setText("-");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, -1, -1));

        cardNoPartText4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jPanel1.add(cardNoPartText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 70, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpurchase/payment.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 46, -1, -1));

        jLabel17.setText("jLabel17");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 273, 18));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpurchase/grey.jpg"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 1, 1000, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        for (int i = (cart.getCurrentCartNumber() - 1); i >= 0; i--)
        {
            try {
                cart.deleteCart(i);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        System.exit(0);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        monthlyPriceText.setText("");
        totalPriceText.setText(Integer.toString(iPrice) + " $");
        
        dMonthlyPrice = 0;
        dTotalPrice = iPrice;
    }//GEN-LAST:event_button1ActionPerformed

    private void monthlyPriceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyPriceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthlyPriceTextActionPerformed

    private void priceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new MyCart().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean text1 = false;
        int number1 = 0;
        Scanner sc1 = new Scanner(cardNoPartText1.getText());
        sc1.useDelimiter("");
        while(sc1.hasNext())
        {
            char ch = sc1.next().charAt(0);
            if(Character.isDigit(ch))
                number1++;
            if(number1 == 4)
                text1 = true;
            if(number1 == 5)
                text1 = false;
        }
        
        boolean text2 = false;
        int number2 = 0;
        Scanner sc2 = new Scanner(cardNoPartText2.getText());
        sc2.useDelimiter("");
        while(sc2.hasNext())
        {
            char ch = sc2.next().charAt(0);
            if(Character.isDigit(ch))
                number2++;
            if(number2 == 4)
                text2 = true;
            if(number2 == 5)
                text2 = false;
        }
        
        boolean text3 = false;
        int number3 = 0;
        Scanner sc3 = new Scanner(cardNoPartText3.getText());
        sc3.useDelimiter("");
        while(sc3.hasNext())
        {
            char ch = sc3.next().charAt(0);
            if(Character.isDigit(ch))
                number3++;
            if(number3 == 4)
                text3 = true;
            if(number3 == 5)
                text3 = false;
        }
        
        boolean text4 = false;
        int number4 = 0;
        Scanner sc4 = new Scanner(cardNoPartText4.getText());
        sc4.useDelimiter("");
        while(sc4.hasNext())
        {
            char ch = sc4.next().charAt(0);
            if(Character.isDigit(ch))
                number4++;
            if(number4 == 4)
                text4 = true;
            if(number4 == 5)
                text4 = false;
        }
        
        if(text1 && text2 && text3 && text4 && (button1.isSelected() || button2.isSelected()))
        {
            new PurchaseSuccesful().setVisible(true);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Wrong or Missing Information");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void monthOptionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthOptionBoxActionPerformed
        if(button2.isSelected())
        updateMonthlyAndTotalPrice();
    }//GEN-LAST:event_monthOptionBoxActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        updateMonthlyAndTotalPrice();
    }//GEN-LAST:event_button2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new MyCart().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new PurchasePanel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        for (int i = (cart.getCurrentCartNumber() - 1); i >= 0; i--)
        {
            try {
                cart.deleteCart(i);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void updateMonthlyAndTotalPrice()
    {
        double dRaiseRate = 0;
        int iMonthNumber = 0;
        
        switch (monthOptionBox.getSelectedIndex()) {
            case 0:
                dRaiseRate = 1.05;
                iMonthNumber = 6;
                break;
            case 1:
                dRaiseRate = 1.1;
                iMonthNumber = 12;
                break;
            case 2:
                dRaiseRate = 1.2;
                iMonthNumber = 24;
                break;
            default:
                dRaiseRate = 1.05;
                iMonthNumber = 6;
                break;
        }
        dTotalPrice = iPrice * dRaiseRate;
        dMonthlyPrice = dTotalPrice / iMonthNumber;
        
        totalPriceText.setText(Double.toString(dTotalPrice) + " $");
        monthlyPriceText.setText(Double.toString(dMonthlyPrice) + " $");
    }
    
    public double getMonthlyPrice()
    {
        return dMonthlyPrice;
    }
    
    public double getTotalPrice()
    {
        return dTotalPrice;
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton button1;
    private javax.swing.JRadioButton button2;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cardNoPartText1;
    private javax.swing.JTextField cardNoPartText2;
    private javax.swing.JTextField cardNoPartText3;
    private javax.swing.JTextField cardNoPartText4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> monthOptionBox;
    private javax.swing.JTextField monthlyPriceText;
    private javax.swing.JTextField priceText;
    private javax.swing.JTextField totalPriceText;
    // End of variables declaration//GEN-END:variables
}
